### ISSUE TITLE
icecat problem

### ISSUE THREAD

**Issue by minervasoluzioni** [haringsrob/Wordpress-Icecat#10]
when i save a nwe product i see in the top of the page : 
"Icecat: You are not allowed to have Full Icecat access"

isn't free?

**Comment by TorlockC** [comment]
Open Icecat is free but they also have a premium version (Full Icecat) too. So it is likely that the product you are saving is part of the Full Icecat catalogue, hence it is not dragging in product information and instead giving this error.

**Comment by haringsrob** [comment]
Correct, by default it will only provide free products, for the full catalogue you will have to upgrade your icecat account.
