### ISSUE TITLE
Integration problems

### ISSUE THREAD

**Issue by bothamic** [haringsrob/Wordpress-Icecat#8]
Good day,
Trust you are well.
We have problems with integration of this product with our products on Woocommerce. We are currently on the newest versions of Wordpress and Woocommerce.
We followed the steps and video available on Youtube exactly to import and populate Products with Icecat, but we keep getting Icecate: Empty Response error. We then go test the EAN id in icecat and it does pick it up in a plain search. Our username and password is also correctly captured. What can be the problem?

Secondly we require help with the WP All Import. Do you have a "how to" to make use of WP All Import together with Icecat grabber? We dont know which field to map where in WP All Import to which, in order to get the EAN, Brand and SKU imported correctly.

Of course the first problem mentioned above should be fixed first otherwise the WP All Import also wont work.

Can you please urgently assist...would be much appreciated.

Thank you.

Kind regards,
M

**Comment by btech69** [comment]
Are you using this plugin: https://github.com/haringsrob/Wordpress-Icecat? If so, it looks like you can use these instructions: http://www.wpallimport.com/documentation/custom-fields/theme-plugin-fields/

**Comment by bothamic** [comment]
Good day,

Yes we are using plugin: https://github.com/haringsrob/Wordpress-Icecat

We did exactly as per the instructions but it still doesnt work. We want it to work with WP All Import for now as we need the basics to work before we can move on to the WP All Import function.

All our settings are correct but it does not pull the data through. Please assist urgently.

Thank you.

**Comment by Miragetek** [comment]
In the wp_all_import manage import section.  You need to add three custom fields when editing the profile.

icecat_ean = {productid[1]}
icecat_sku = {sellersku[1]}
icecat_brand = {brandname[1]}

or whatever the corresponding fields are from your csv source.
in (wordpress) settings -> icecat Data Grabber - make sure all of the boxes are ticked.

you can now run an import and icecat will be queried to fill in the blanks in your product posts.

*** please note - depending what you select to be updated in your records this can make the import process Very Slow ***  (one of my current issues) lol.

**Comment by bothamic** [comment]
Good day.
Thank you.
Yes I managed to pull in the EAN for all items via WP All Import. But when publishing, no content is being pulled from Icecat? That is my big problem. I aslo tried manually adding a new item and entering a valid EAN, which is currently available on Icecat, then published but still no data is being pulled from Icecat.

All my settings, username, password etc is correct under the Icecat Grabber setting and i have the newest version of the plugin.

What can be the problem then?

**Comment by Miragetek** [comment]
Hi,
Main thing I can think of… Have you purchased the pro version of WP all import?  The free version doesn’t work with any plugins.

Regards
Ben

**Comment by bothamic** [comment]
Yes i have the pro version of WP All Import.

The problem is between the Icecat Grabber plugin and Icecat because even if i create a new product manually in woocommerce and add a test title and populate the Icecat EAN column in the product page and publish it, it doesnt pull any data from Icecat. The EAN does exist in Icecat so i dont know why the Icecat plugin doesnt pull the data? If been asking for help for months now but no one can give me an answer of why the calls return empty from Icecat. 






---- On Thu, 29 Aug 2019 18:38:11 +0200 notifications@github.com wrote ----


Hi,
Main thing I can think of… Have you purchased the pro version of WP all import? The free version doesn’t work with any plugins.

Regards
Ben

**Comment by Miragetek** [comment]
Do you have access to ssh and WP-cli in your hosting environment?

To try and fix my speed issue I have been launching the import process from an ssh session.  While it runs you get some error messages being sent to the console that are normally hidden.  They may help you work out what is wrong.  Example below.  Items between <> are placeholders replace them and the <> with the required info.

php -r 'parse_str("import_key=<your secret Key from import settings page>&import_id=<your job id from manage imports page >&action=trigger", $_GET); include "wp-cron.php";'

php -r 'parse_str("import_key=<your secret Key from import settings page>&import_id=<your job id from manage imports page >&action=processing", $_GET); include "wp-cron.php";'

I get the following errors that say part of the url is invalid

PHP Warning:  file_get_contents(http://data.icecat.biz/xml_s3/xml_server3.cgi?prod_id=**********;lang=en;output=productxml;vendor=*************;): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

in /home/*********/site/public_html/wp-content/plugins/Wordpress-Icecat-master/Icecat/Icecat.php on line 84

Apart from that I don’t think I can help much more.

Best of luck
Regards
Ben

**Comment by bothamic** [comment]
Thank you appreciate it.

Yes if I can just see a log of what the errors are I know what it might be.

Will have a look thank you.

Regards,
Michael




---- On Thu, 29 Aug 2019 19:09:01 +0200 notifications@github.com wrote ----


Do you have access to ssh and WP-cli in your hosting environment?

To try and fix my speed issue I have been launching the import process from an ssh session. While it runs you get some error messages being sent to the console that are normally hidden. They may help you work out what is wrong. Example below. Items between <> are placeholders replace them and the <> with the required info.

php -r 'parse_str("import_key=<your secret Key from import settings page>&import_id=<your job id from manage imports page >&action=trigger", $_GET); include "wp-cron.php";'

php -r 'parse_str("import_key=<your secret Key from import settings page>&import_id=<your job id from manage imports page >&action=processing", $_GET); include "wp-cron.php";'

I get the following errors that say part of the url is invalid

PHP Warning: file_get_contents(http://data.icecat.biz/xml_s3/xml_server3.cgi?prod_id=**********;lang=en;output=productxml;vendor=*************;): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

in /home/*********/site/public_html/wp-content/plugins/Wordpress-Icecat-master/Icecat/Icecat.php on line 84

Apart from that I don’t think I can help much more.

Best of luck
Regards
Ben

**Comment by haringsrob** [comment]
Thank you @Miragetek for helping to resolve this issue.

I can confirm that only wp all import pro works with custom fields which is what this plugin does.

As for the empty response. There can be many things, it might even be so that the plugin requests data in a format no longer supported by icecat.
