### ISSUE TITLE
calling update process from own script

### ISSUE THREAD

**Issue by Miragetek** [haringsrob/Wordpress-Icecat#9]
Hi,
feeling a bit thick as I cannot work out how to call the icecat_get_data($post_id) function from my own code.

I've got a harness script for WP-cli that runs a wp_query to select a list of posts and then processes the list with a nice looking progress bar.

I just need to know what I need to put in order to run the datagrabber function against the selected posts.

If I try to use require_once i get a bunch of errors.  If I try and just call the function (as the plugin is already loaded by wordpress) it looks like it is working but none of the posts get updated.

Looking at the icecat_disabled attribute on the affected posts to confirm that they have been updated.

Any help would be appreciated.

**Comment by haringsrob** [comment]
I honestly don't know how wordpress handles file inclusions. The errors might be normal if you use a modern php version, this code is pretty old(school).

I think your best bet is to take out these functions into a separate file and run them from there by requiring it.
